# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
# user = CreateAdminService.new.call
# puts 'CREATED ADMIN USER: ' << user.email

answers = Answer.create!([
	{name: 'Tails', super_bowl_id: 2},
	{name: 'Heads', super_bowl_id: 2},
	{name: 'New England Patriots', super_bowl_id: 2},
	{name: 'Philadelphia Eagles', super_bowl_id: 2},
	{name: 'Yes', super_bowl_id: 2},
	{name: 'No', super_bowl_id: 2},
	{name: 'Over', super_bowl_id: 2},
	{name: 'Under', super_bowl_id: 2},
	{name: 'Even', super_bowl_id: 2},
	{name: 'Odd', super_bowl_id: 2},
	{name: '1st Quarter', super_bowl_id: 2},
	{name: '2nd Quarter', super_bowl_id: 2},
	{name: '3rd Quarter', super_bowl_id: 2},
	{name: '4th Quarter', super_bowl_id: 2},
	{name: '1st Half', super_bowl_id: 2},
	{name: '2nd Half', super_bowl_id: 2},
	{name: 'Patriots Touchdown', super_bowl_id: 2},
	{name: 'Patriots Field Goal', super_bowl_id: 2},
	{name: 'Patriots Safety', super_bowl_id: 2},
	{name: 'Eagles Touchdown', super_bowl_id: 2},
	{name: 'Eagles Field Goal', super_bowl_id: 2},
	{name: 'Eagles Safety', super_bowl_id: 2},
	{name: 'Fumble', super_bowl_id: 2},
	{name: 'Interception', super_bowl_id: 2},
	{name: 'Safety', super_bowl_id: 2},
	{name: 'No Turnover in game', super_bowl_id: 2},
	{name: 'Complete', super_bowl_id: 2},
	{name: 'Incomplete', super_bowl_id: 2},
	{name: 'Play Stands', super_bowl_id: 2},
	{name: 'Play Reversed', super_bowl_id: 2},
	{name: 'None', super_bowl_id: 2},
	{name: 'Orange', super_bowl_id: 2},
	{name: 'Yellow', super_bowl_id: 2},
	{name: 'Blue', super_bowl_id: 2},
	{name: 'Green', super_bowl_id: 2},
	{name: 'Purple', super_bowl_id: 2},
	{name: 'Red', super_bowl_id: 2},
	{name: 'Clear', super_bowl_id: 2},
	{name: 'None', super_bowl_id: 2},
	{name: 'PHI: Nick Foles', super_bowl_id: 2},
	{name: 'PHI: Jay Ajayi', super_bowl_id: 2},
	{name: 'PHI: Alshon Jeffery', super_bowl_id: 2},
	{name: 'PHI: Torrey Smith', super_bowl_id: 2},
	{name: 'PHI: Nelson Agholor', super_bowl_id: 2},
	{name: 'PHI: Zach Ertz', super_bowl_id: 2},
	{name: 'PHI: Brandon Graham', super_bowl_id: 2},
	{name: 'PHI: Fletcher Cox', super_bowl_id: 2},
	{name: 'PHI: Timmy Jernigan', super_bowl_id: 2},
	{name: 'PHI: Vinny Curry', super_bowl_id: 2},
	{name: 'PHI: Nigel Bradham', super_bowl_id: 2},
	{name: 'PHI: Mychal Kendricks', super_bowl_id: 2},
	{name: 'PHI: Jalen Mills', super_bowl_id: 2},
	{name: 'PHI: Ronald Darby', super_bowl_id: 2},
	{name: 'PHI: Patrick Robinson', super_bowl_id: 2},
	{name: 'PHI: Rodney McLeod', super_bowl_id: 2},
	{name: 'PHI: Malcolm Jenkins', super_bowl_id: 2},
	{name: 'PHI: Jake Elliott', super_bowl_id: 2},
	{name: 'PHI: Donnie Jones', super_bowl_id: 2},
	{name: 'PHI: Kenjon Barner', super_bowl_id: 2},
	{name: 'PHI: Nate Sudfeld', super_bowl_id: 2},
	{name: 'PHI: LeGarrette Blount', super_bowl_id: 2},
	{name: 'PHI: Corey Clement', super_bowl_id: 2},
	{name: 'PHI: Mack Hollins', super_bowl_id: 2},
	{name: 'PHI: Brent Celek', super_bowl_id: 2},
	{name: 'PHI: Trey Burton', super_bowl_id: 2},
	{name: 'PHI: Chris Long', super_bowl_id: 2},
	{name: 'PHI: Derek Barnett', super_bowl_id: 2},
	{name: 'PHI: Beau Allen', super_bowl_id: 2},
	{name: 'PHI: Destiny Vaeao', super_bowl_id: 2},
	{name: 'PHI: Dannell Ellerbe', super_bowl_id: 2},
	{name: 'PHI: Najee Goode', super_bowl_id: 2},
	{name: 'PHI: Corey Graham', super_bowl_id: 2},
	{name: 'PATS: Tom Brady', super_bowl_id: 2},
	{name: 'PATS: Dion Lewis', super_bowl_id: 2},
	{name: 'PATS: Brandin Cooks', super_bowl_id: 2},
	{name: 'PATS: Chris Hogan', super_bowl_id: 2},
	{name: 'PATS: Danny Amendola', super_bowl_id: 2},
	{name: 'PATS: Rob Gronkowski', super_bowl_id: 2},
	{name: 'PATS: Trey Flowers', super_bowl_id: 2},
	{name: 'PATS: Malcom Brown', super_bowl_id: 2},
	{name: 'PATS: Lawrence Guy', super_bowl_id: 2},
	{name: 'PATS: Ricky Jean Francois', super_bowl_id: 2},
	{name: 'PATS: Kyle Van Noy', super_bowl_id: 2},
	{name: 'PATS: Elandon Roberts', super_bowl_id: 2},
	{name: 'PATS: James Harrison', super_bowl_id: 2},
	{name: 'PATS: Malcolm Butler', super_bowl_id: 2},
	{name: 'PATS: Stephon Gilmore', super_bowl_id: 2},
	{name: 'PATS: Devin McCourty', super_bowl_id: 2},
	{name: 'PATS: Patrick Chung', super_bowl_id: 2},
	{name: 'PATS: Stephen Gostkowski', super_bowl_id: 2},
	{name: 'PATS: Ryan Allen', super_bowl_id: 2},
	{name: 'PATS: Brian Hoyer', super_bowl_id: 2},
	{name: 'PATS: James White', super_bowl_id: 2},
	{name: 'PATS: Rex Burkhead', super_bowl_id: 2},
	{name: 'PATS: Brandon Bolden', super_bowl_id: 2},
	{name: 'PATS: James Develin', super_bowl_id: 2},
	{name: 'PATS: Phillip Dorsett', super_bowl_id: 2},
	{name: 'PATS: Matthew Slater', super_bowl_id: 2},
	{name: 'PATS: Dwayne Allen', super_bowl_id: 2},
	{name: 'PATS: Jacob Hollister', super_bowl_id: 2},
	{name: 'PATS: Eric Lee', super_bowl_id: 2},
	{name: 'PATS: Deatrich Wise', super_bowl_id: 2},
	{name: 'PATS: Adam Butler', super_bowl_id: 2},
	{name: 'PATS: Marquis Flowers', super_bowl_id: 2},
	{name: 'PATS: Geneo Grissom', super_bowl_id: 2},
	{name: 'PATS: Nicholas Grigsby', super_bowl_id: 2},
	{name: 'PATS: Eric Rowe', super_bowl_id: 2},
	{name: 'PATS: Jonathan Jones', super_bowl_id: 2},
	{name: 'PATS: Duron Harmon', super_bowl_id: 2},
	{name: 'PATS: Jordan Richards', super_bowl_id: 2}

	])